"""empty message

Revision ID: 2e4f9fc369d4
Revises: e63c8b89c157
Create Date: 2022-05-26 19:36:07.487588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e4f9fc369d4'
down_revision = 'e63c8b89c157'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todolists', 'select',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todolists', 'select',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
