"""empty message

Revision ID: 67d759beb083
Revises: 11f9053241fe
Create Date: 2022-05-26 18:55:34.133041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67d759beb083'
down_revision = '11f9053241fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todolists',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('lname', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('todos', sa.Column('lid', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'todos', 'todolists', ['lid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_column('todos', 'lid')
    op.drop_table('todolists')
    # ### end Alembic commands ###
