"""empty message

Revision ID: e63c8b89c157
Revises: 67d759beb083
Create Date: 2022-05-26 19:34:45.482297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e63c8b89c157'
down_revision = '67d759beb083'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todolists', sa.Column('select', sa.Boolean(), nullable=True))
    op.alter_column('todos', 'lid',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'lid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('todolists', 'select')
    # ### end Alembic commands ###
